config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'home#index'
  resources :calendar, only: [:index]
  resources :circuits, only: [:show]
  resources :standings, only: [:index]
  resources :drivers, only: [:show]
  resources :profile, only: [:index]
  resources :bets, only: [:index, :new, :create, :show]
  resources :rankings, only: [:index] do
    get 'last_race', on: :collection
    get 'season', on: :collection
  end

end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  
  def index

  end

  def last_race
    b = Bet.where(circuit: F1Circuit.last_race.code, year: Date.today.year, validated: true).order(result_points: :desc)
    @bets = b.map.with_index { |x, i| [i+1, x] }.to_h
  end

  def season
    b = BetPoint.where(year: Date.today.year).order(points: :desc)
    @bets = b.map.with_index { |x, i| [i+1, x] }.to_h
    @year = Date.today.year
  end
end

app/views/rankings/index.html.erb
<div>
  <%= link_to 'Última corrida', last_race_rankings_path, class: 'links' %>
</div>

<div>
  <%= link_to 'Campeonato atual', season_rankings_path, class: 'links' %>
</div>

app/views/rankings/last_race.html.erb
<% unless @bets.empty? %>
  <table class="<%= controller_name %>-table">

    <thead>
      <th>Posição</th>
      <th>Pontuação</th>
      <th>ID da aposta</th>
      <th>Usuário</th>
    </thead>

    <tbody>
      <% @bets.each do |key, value|%>
          <tr id="bet-<%= value.id %>">
            <td><%= key %></td>
            <td><%=value.result_points%> pts</td>
            <td>ID: <%=value.id%></td>
            <td><%=value.user.email%></td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  
<% end %>

app/views/rankings/season.html.erb
<% unless @bets.empty? %>

  <h1> Temporada: <%= @year %></h1>

  <table class="<%= controller_name %>-table">

    <thead>
      <th>Posição</th>
      <th>Pontuação</th>
      <th>Usuário</th>
    </thead>

    <tbody>
      <% @bets.each do |key, value|%>
          <tr id="bt-<%= value.id %>">
            <td><%= key %></td>
            <td><%=value.points%> pts</td>
            <td><%=value.user.email%></td>
          </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h1>Não existem apostas cadastradas</h1>
<% end %>